modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/dragon-forge/SimpleQuarry/issues"
license="All rights reserved"

[[mods]]
modId="squarry"
version="${file.jarVersion}"
displayName="Simple Quarry"
updateJSONURL="http://h.zeith.org/api/fmluc/247393"
displayURL="http://h.zeith.org/api/fmlhp/247393"
# logoFile="examplemod.png"
authors="Zeitheron"

description='''
Simple mod that adds a simple quarry. Or two.
'''

[[dependencies.squarry]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.squarry]]
    modId="minecraft"
    mandatory=true
    versionRange = "[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.squarry]]
    modId="hammerlib"
    mandatory=true
    versionRange = "[19.4.47,)"
    ordering="AFTER"
    side="BOTH"
