modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://gitlab.com/DragonForge/SimpleQuarry/issues"
license="All rights reserved"
[[mods]]
modId="squarry"
version="${file.jarVersion}"
displayName="Simple Quarry"
updateJSONURL="http://dccg.herokuapp.com/api/fmluc/247393"
displayURL="http://dccg.herokuapp.com/api/fmlhp/247393"
logoFile="examplemod.png" #optional
authors="Zeitheron" #optional
description='''
Simple mod that adds a simple quarry. Or two.
'''
[[dependencies.squarry]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE" # NONE/BEFORE/AFTER
    side="BOTH"
[[dependencies.squarry]]
    modId="minecraft"
    mandatory=true
    versionRange = "[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.squarry]]
    modId="hammerlib"
    mandatory=true
    versionRange = "[19.2.35,)"
    ordering="NONE"
    side="BOTH"
